export default [
  {
    "group": "PÃES E SIMILARES",
    "food": [
      "Biscoito Água e sal,4 unidades",
      "Biscoito de Aveia,4 unidades",
      "Biscoito Amanteigado sem recheio,3 unidades",
      "Biscoite Cream Cracker,4 unidades",
      "Biscoito Salgadinhos(Elma Chips)",
      "Biscoito Polvilho,8 roscas",
      "Biscoito Wafer,1 ½ unidades",
      "Biscoito de Arroz Integral,13 unidades",
      "Bolo Simples,2 pedaços(50g)",
      "Bolo de Banana,2 pedaços(60g)",
      "Panetone,1 fatia Fina",
      "Mix de Castanhas,30g",
      "Goma de Tapioca,30g",
      "Pão de Batata ,½ unidade média",
      "Pão de Forma ,1 Fatia",
      "Pão de Queijo,1 unidade",
      "Pão Doce ,½ unidade média",
      "Pipoca salgada ou doce,25g",
      "Sucrilhos ,1 copo pequeno",
      "Cereal c/ açúcar,7 colheres de sopa",
      "Cereal s/ açúcar,2 xícaras de chá",
      "Granola,25g",
      "Pamonha,½ unidade",
      "Trigo ,2 colheres de sopa",
      "Torrada,3 unidades",
      "Torrada de Pão Francês,3 fatias",
      "Pão Caseiro,1 fatia fina",
      "Pão de Centeio,1 fatia",
      "Pão de Integral,1 fatia",
      "Pão de Glúten ,2 fatias",
      "Pão Sírio,1 unidade pequena",
      "Pão de Hambúrguer ,½ unidade",
      "Pão de Cachorro Quente,½ unidade",
      "Pão Frances ,½ unidade"
    ]
  },
  {
    "group": "CEREAIS E SIMILARES",
    "food": [
      "Arroz Branco,100g",
      "Arroz Integral,110g",
      "Macarrão a Bolonhesa, Alho e Óleo, Molho Branco e Ao Sugo",
      "Batata Doce cozida,130g",
      "Polenta,3 colheres de sopa",
      "Polenta Frita,1 unidade média",
      "Mandioca Cozida,100g",
      "Mandioca Frita",
      "Batata Inglesa Cozida,250g",
      "Purê de Batata,3 colheres de sopa",
      "Noque,3 colheres de sopa",
      "Milho Verde Cozido,1 espiga média",
      "Milho Verde Enlatado,2 colheres de sopa",
      "Pizza(calabresa, frango c/ milho, mussarela e vegetariana),1 pedaço médio",
      "Panqueca,2 unidades pequenas",
      "Lasanha,1 pedaço",
      "Bolinho de Arroz,2 unidades",
      "Inhame Cozido,120g",
      "Esfirrra,1 unidade média",
      "Farinha de Mandioca e de milho,2 colheres de sopa",
      "Farofa,2 colheres de sopa",
      "Pirão,2 colheres de sopa",
      "Sushi de Salmão ou Atum,7 unidades pequenas"
    ]
  },
  {
    "group": "LEGUMINOSAS E SIMILARES",
    "food": [
      "Ervilha Seca Cozida,3 colheres de sopa",
      "Feijão Branco,3 colheres de sopa",
      "Feijão Preto,3 colheres de sopa",
      "Grão de Bico,2 colheres de sopa",
      "Lentilha,2 colheres de sopa"
    ]
  },
  {
    "group": "Oleaginosas",
    "food": [
      "Amêndoas,10 unidades",
      "Avelã,9 unidades",
      "Castanha do Pará,2 unidades",
      "Castanha do Cajú,5 unidades",
      "Nozes,2 unidades",
      "Macadâmia,3 unidades"
    ]
  },
  {
    "group": "CARNES",
    "food": [
      "Almôndegas de Carne Bovina,100g",
      "Bife Grelhado,100g",
      "Bife à Milanesa,60g",
      "Bife Rolê,80g",
      "Carne Assada,100g",
      "Carne de Porco Magra,85g",
      "Carne Ensopada,100g",
      "Carne Seca,60g",
      "Carne Cozida,100g",
      "Carne Moída Cozida,100g",
      "Dobradinha,65g",
      "Língua,60g",
      "Linguiça de Frango Grelhada,80g",
      "Lombo de Porco,1 fatia (85g)",
      "Frango Grelhado,1 filé médio (100g)",
      "Hamburguer Caseiro,90g",
      "Omelete Simples,1 unidade com 3 ovos",
      "Ovo Pochê,3 unidades",
      "Ovo de Codorna Cozido,10 unidades",
      "Ovo de Galinha Mexido,",
      "Sardinha Fresca,1 pedaço médio",
      "Sardinha em Conserva,1 unidade pequena(80g)",
      "Sashimi de Atum ou Salmão,10 unidades (80g)",
      "Peito de Frango Assado,100g",
      "Peixe Grelhado,130g",
      "Peixe(posta),120g",
      "Atum em conserva,40g",
      "Bobó de Camarão,",
      "Bacalhau,1 filé médio(100g)",
      "Sobrecoxa de Frango Assada,1 unidades grande ou 2 pequenas",
      "Coração,9 unidades",
      "Frango Desfiado peito,120g"
    ]
  },
  {
    "group": "VEGETAL A (Á VONTADE)",
    "food": [
      "Acelga",
      "Couve-Flor",
      "Agrião",
      "Endívia",
      "Aipo",
      "Escarola",
      "Alho",
      "Espinafre",
      "Alho Poro",
      "Jiló",
      "Almeirão",
      "Maxixe",
      "Aspargo",
      "Mostarda",
      "Alface",
      "Bertalha",
      "Nabo",
      "Broto de Feijão",
      "Palmito",
      "Cebola",
      "Pepino",
      "Cebolinha",
      "Pimentão",
      "Champignon",
      "Rabanete",
      "Chicória",
      "Repolho",
      "Cogumelo",
      "Rúcula",
      "Couve",
      "Salsão",
      "Taioba",
      "Tomate"
    ]
  },
  {
    "group": "VEGETAL B",
    "food": [
      "Abobora",
      "Chuchu Cozido",
      "Abobrinha",
      "Quiabo",
      "Berinjela Cozida",
      "Vagem",
      "Beterraba Crua",
      "Azeitona Preta ou Verde,7 unidades",
      "Brócolis Cozido",
      "Cenoura Crua"
    ]
  },
  {
    "group": "GORDURAS E SIMILARES",
    "food": [
      "Azeite de Oliva,1 colher de sobremesa",
      "Geléia,2 colheres de chá",
      "Maionese,1 colher de chá",
      "Manteiga,1 colher de chá",
      "Mortadela,1 fatia média",
      "Óleo de Canola ou de Girassol,1 colher de sobremesa",
      "Presunto,1 fatia media",
      "Salame,1 fatia média",
      "Pasta de Amendoim,15 gramas"
    ]
  },
  {
    "group": "FRUTAS",
    "food": [
      "Abacate,½ unidade",
      "Abacaxi,2 fatias finas",
      "Acerola,6 unidades",
      "Ameixa,3 unidades",
      "Amora,15 unidades",
      "Banana,1 unidade",
      "CAjú,1 unidade",
      "Caqui,1 unidade pequena",
      "Carambola,1 unidade",
      "Coco Fresco(ralado),2 colheres de sopa",
      "Cranberry Desidratado,1 colher de sopa",
      "Damasco Desidratado,3 unidades",
      "Figo,1 unidade",
      "Fruta do Conde,1 unidade pequena",
      "Goiaba,½ unidade",
      "Jabuticaba,15 unidades",
      "Jaca,4 polpas",
      "Kiwi,1 unidade",
      "Laranja,1 unidade",
      "Maçã,1 unidade",
      "Mamão Papaia,½ unidade pequena",
      "Manga,1 unidade pequena",
      "Melancia,1 fatia média",
      "Melão,1 fatia grande",
      "Morango,10 unidades",
      "Nectarina,1 unidade grande",
      "Pêra,1 unidade grande",
      "Pitanga,15 unidades",
      "Ponkan,1 unidade média",
      "Suco de Abacaxi,120 ml",
      "Suco de Laranja Puro,180 ml",
      "Suco de Mexerica,180 ml",
      "Uva,1 cacho pequeno",
      "Uva Passa,1 colher de sopa"
    ]
  }
]
